// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using s20601.Data;

#nullable disable

namespace s20601.Migrations
{
    [DbContext(typeof(S20601Context))]
    partial class S20601ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupOwnership", b =>
                {
                    b.Property<int>("IdOwner")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.HasKey("IdOwner", "IdGroup")
                        .HasName("GroupOwnership_pk");

                    b.HasIndex("IdGroup");

                    b.ToTable("GroupOwnership", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("Permission_Id")
                        .HasColumnType("int");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.HasKey("Permission_Id", "Role_Id")
                        .HasName("PermissionRole_pk");

                    b.HasIndex("Role_Id");

                    b.ToTable("PermissionRole", (string)null);
                });

            modelBuilder.Entity("s20601.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("ActivityType_pk");

                    b.ToTable("ActivityType", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int?>("IdComment")
                        .HasColumnType("int");

                    b.Property<int>("IdPost")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("Id")
                        .HasName("Comment_pk");

                    b.HasIndex("IdComment");

                    b.HasIndex("IdPost");

                    b.HasIndex("IdUser");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("Crew_pk");

                    b.ToTable("Crew", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("Genre_pk");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varbinary(100)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("Group_pk");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("s20601.Models.GroupMembership", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("IdUser", "IdGroup")
                        .HasName("GroupMembership_pk");

                    b.HasIndex("IdGroup");

                    b.ToTable("GroupMembership", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<int>("Created")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliverTime")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("IdRecipient")
                        .HasColumnType("int");

                    b.Property<int>("IdSender")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("Message_pk");

                    b.HasIndex("IdRecipient");

                    b.HasIndex("IdSender");

                    b.HasIndex("IdStatus");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("Movie_pk");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieCollection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("MovieCollection_pk");

                    b.ToTable("MovieCollection", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieCollectionMovie", b =>
                {
                    b.Property<int>("IdMovieCollection")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdMovieCollection")
                        .HasName("MovieCollectionMovie_pk");

                    b.HasIndex("Movie_Id");

                    b.ToTable("MovieCollectionMovie", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieCollectionUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdMovieCollection")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("MovieCollectionUser_pk");

                    b.HasIndex("IdMovieCollection");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "IdUser", "IdMovieCollection", "IdRole" }, "MovieCollectionUser_ak_1")
                        .IsUnique();

                    b.ToTable("MovieCollectionUser", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieCrew", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCrew")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("MovieCrew_pk");

                    b.HasIndex("IdCrew");

                    b.HasIndex("Movie_Id");

                    b.ToTable("MovieCrew", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieGenre", b =>
                {
                    b.Property<int>("IdMovieGenre")
                        .HasColumnType("int");

                    b.Property<int>("Genre_Id")
                        .HasColumnType("int");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdMovieGenre")
                        .HasName("MovieGenre_pk");

                    b.HasIndex("Genre_Id");

                    b.HasIndex("Movie_Id");

                    b.ToTable("MovieGenre", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieOfTheDay", b =>
                {
                    b.Property<string>("Movie_Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Date")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("Movie_Id")
                        .HasName("MovieOfTheDay_pk");

                    b.ToTable("MovieOfTheDay", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieRate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("MovieRate_pk");

                    b.HasIndex("Movie_Id");

                    b.HasIndex(new[] { "IdUser", "Movie_Id" }, "UniqueRating")
                        .IsUnique();

                    b.ToTable("MovieRate", (string)null);
                });

            modelBuilder.Entity("s20601.Models.MovieUpdateRequest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("MovieUpdateRequest_pk");

                    b.HasIndex("IdUser");

                    b.HasIndex("Movie_Id");

                    b.ToTable("MovieUpdateRequest", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("Permission_pk");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifiedAt")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id")
                        .HasName("Post_pk");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdUser");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Review", b =>
                {
                    b.Property<int>("IdAuthor")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Movie_Id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdAuthor")
                        .HasName("Review_pk");

                    b.HasIndex("Movie_Id");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("s20601.Models.ReviewRate", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<bool>("Rating")
                        .HasColumnType("bit");

                    b.Property<int>("Review_IdAuthor")
                        .HasColumnType("int");

                    b.HasKey("IdUser")
                        .HasName("ReviewRate_pk");

                    b.HasIndex("Review_IdAuthor");

                    b.ToTable("ReviewRate", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("Role_pk");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("s20601.Models.SocialActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActivityAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("IdActivityType")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("SocialActivityLog_pk");

                    b.HasIndex("IdActivityType");

                    b.HasIndex("IdUser");

                    b.ToTable("SocialActivityLog", (string)null);
                });

            modelBuilder.Entity("s20601.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("Status_pk");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("s20601.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("LastLogin")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileDescription")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("ProfileImage")
                        .HasMaxLength(100)
                        .HasColumnType("varbinary(100)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("User_pk");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("s20601.Models.UserRelationship", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdRelatedUser")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUser", "IdRelatedUser")
                        .HasName("UserRelationship_pk");

                    b.HasIndex("IdRelatedUser");

                    b.ToTable("UserRelationship", (string)null);
                });

            modelBuilder.Entity("GroupOwnership", b =>
                {
                    b.HasOne("s20601.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("IdGroup")
                        .IsRequired()
                        .HasConstraintName("GroupOwnership_Group");

                    b.HasOne("s20601.Models.User", null)
                        .WithMany()
                        .HasForeignKey("IdOwner")
                        .IsRequired()
                        .HasConstraintName("GroupOwnership_User");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("s20601.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("Permission_Id")
                        .IsRequired()
                        .HasConstraintName("PermissionRole_Permission");

                    b.HasOne("s20601.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .IsRequired()
                        .HasConstraintName("PermissionRole_Role");
                });

            modelBuilder.Entity("s20601.Models.Comment", b =>
                {
                    b.HasOne("s20601.Models.Comment", "IdCommentNavigation")
                        .WithMany("InverseIdCommentNavigation")
                        .HasForeignKey("IdComment")
                        .HasConstraintName("Comment_Comment");

                    b.HasOne("s20601.Models.Post", "IdPostNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdPost")
                        .IsRequired()
                        .HasConstraintName("Comment_Post");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("Comment_User");

                    b.Navigation("IdCommentNavigation");

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.GroupMembership", b =>
                {
                    b.HasOne("s20601.Models.Group", "IdGroupNavigation")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("IdGroup")
                        .IsRequired()
                        .HasConstraintName("GroupMembership_Group");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("GroupMembership_User");

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.Message", b =>
                {
                    b.HasOne("s20601.Models.User", "IdRecipientNavigation")
                        .WithMany("MessageIdRecipientNavigations")
                        .HasForeignKey("IdRecipient")
                        .IsRequired()
                        .HasConstraintName("Message_Recipient");

                    b.HasOne("s20601.Models.User", "IdSenderNavigation")
                        .WithMany("MessageIdSenderNavigations")
                        .HasForeignKey("IdSender")
                        .IsRequired()
                        .HasConstraintName("Message_Sender");

                    b.HasOne("s20601.Models.Status", "IdStatusNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("IdStatus")
                        .IsRequired()
                        .HasConstraintName("Message_Status");

                    b.Navigation("IdRecipientNavigation");

                    b.Navigation("IdSenderNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("s20601.Models.MovieCollectionMovie", b =>
                {
                    b.HasOne("s20601.Models.MovieCollection", "IdMovieCollectionNavigation")
                        .WithOne("MovieCollectionMovie")
                        .HasForeignKey("s20601.Models.MovieCollectionMovie", "IdMovieCollection")
                        .IsRequired()
                        .HasConstraintName("MovieCollectionMovie_MovieCollection");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("MovieCollectionMovies")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieCollectionMovie_Movie");

                    b.Navigation("IdMovieCollectionNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.MovieCollectionUser", b =>
                {
                    b.HasOne("s20601.Models.MovieCollection", "IdMovieCollectionNavigation")
                        .WithMany("MovieCollectionUsers")
                        .HasForeignKey("IdMovieCollection")
                        .IsRequired()
                        .HasConstraintName("MovieCollectionUsers_MovieCollection");

                    b.HasOne("s20601.Models.Role", "IdRoleNavigation")
                        .WithMany("MovieCollectionUsers")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("MovieCollectionUsers_Role");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("MovieCollectionUsers")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("MovieCollectionUsers_User");

                    b.Navigation("IdMovieCollectionNavigation");

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.MovieCrew", b =>
                {
                    b.HasOne("s20601.Models.Crew", "IdCrewNavigation")
                        .WithMany("MovieCrews")
                        .HasForeignKey("IdCrew")
                        .IsRequired()
                        .HasConstraintName("MovieCrew_Crew");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("MovieCrews")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieCrew_Movie");

                    b.Navigation("IdCrewNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.MovieGenre", b =>
                {
                    b.HasOne("s20601.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Genre_Id")
                        .IsRequired()
                        .HasConstraintName("MovieGenre_Genre");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieGenre_Movie");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.MovieOfTheDay", b =>
                {
                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithOne("MovieOfTheDay")
                        .HasForeignKey("s20601.Models.MovieOfTheDay", "Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieOfTheDay_Movie");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.MovieRate", b =>
                {
                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("MovieRates")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("MovieRate_User");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("MovieRates")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieRate_Movie");

                    b.Navigation("IdUserNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.MovieUpdateRequest", b =>
                {
                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("MovieUpdateRequests")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("MovieUpdateRequest_User");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("MovieUpdateRequests")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("MovieUpdateRequest_Movie");

                    b.Navigation("IdUserNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.Post", b =>
                {
                    b.HasOne("s20601.Models.Group", "IdGroupNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdGroup")
                        .IsRequired()
                        .HasConstraintName("Post_Group");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("Post_User");

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.Review", b =>
                {
                    b.HasOne("s20601.Models.User", "IdAuthorNavigation")
                        .WithOne("Review")
                        .HasForeignKey("s20601.Models.Review", "IdAuthor")
                        .IsRequired()
                        .HasConstraintName("Review_User");

                    b.HasOne("s20601.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("Movie_Id")
                        .IsRequired()
                        .HasConstraintName("Review_Movie");

                    b.Navigation("IdAuthorNavigation");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("s20601.Models.ReviewRate", b =>
                {
                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithOne("ReviewRate")
                        .HasForeignKey("s20601.Models.ReviewRate", "IdUser")
                        .IsRequired()
                        .HasConstraintName("ReviewRate_User");

                    b.HasOne("s20601.Models.Review", "Review_IdAuthorNavigation")
                        .WithMany("ReviewRates")
                        .HasForeignKey("Review_IdAuthor")
                        .IsRequired()
                        .HasConstraintName("ReviewRate_Review");

                    b.Navigation("IdUserNavigation");

                    b.Navigation("Review_IdAuthorNavigation");
                });

            modelBuilder.Entity("s20601.Models.SocialActivityLog", b =>
                {
                    b.HasOne("s20601.Models.ActivityType", "IdActivityTypeNavigation")
                        .WithMany("SocialActivityLogs")
                        .HasForeignKey("IdActivityType")
                        .IsRequired()
                        .HasConstraintName("ActivityLog_ActivityType");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("SocialActivityLogs")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("ActivityLog_User");

                    b.Navigation("IdActivityTypeNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.UserRelationship", b =>
                {
                    b.HasOne("s20601.Models.User", "IdRelatedUserNavigation")
                        .WithMany("UserRelationshipIdRelatedUserNavigations")
                        .HasForeignKey("IdRelatedUser")
                        .IsRequired()
                        .HasConstraintName("UserRelationship_User2");

                    b.HasOne("s20601.Models.User", "IdUserNavigation")
                        .WithMany("UserRelationshipIdUserNavigations")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("UserRelationship_User1");

                    b.Navigation("IdRelatedUserNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("s20601.Models.ActivityType", b =>
                {
                    b.Navigation("SocialActivityLogs");
                });

            modelBuilder.Entity("s20601.Models.Comment", b =>
                {
                    b.Navigation("InverseIdCommentNavigation");
                });

            modelBuilder.Entity("s20601.Models.Crew", b =>
                {
                    b.Navigation("MovieCrews");
                });

            modelBuilder.Entity("s20601.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("s20601.Models.Group", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("s20601.Models.Movie", b =>
                {
                    b.Navigation("MovieCollectionMovies");

                    b.Navigation("MovieCrews");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieOfTheDay");

                    b.Navigation("MovieRates");

                    b.Navigation("MovieUpdateRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("s20601.Models.MovieCollection", b =>
                {
                    b.Navigation("MovieCollectionMovie");

                    b.Navigation("MovieCollectionUsers");
                });

            modelBuilder.Entity("s20601.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("s20601.Models.Review", b =>
                {
                    b.Navigation("ReviewRates");
                });

            modelBuilder.Entity("s20601.Models.Role", b =>
                {
                    b.Navigation("MovieCollectionUsers");
                });

            modelBuilder.Entity("s20601.Models.Status", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("s20601.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GroupMemberships");

                    b.Navigation("MessageIdRecipientNavigations");

                    b.Navigation("MessageIdSenderNavigations");

                    b.Navigation("MovieCollectionUsers");

                    b.Navigation("MovieRates");

                    b.Navigation("MovieUpdateRequests");

                    b.Navigation("Posts");

                    b.Navigation("Review");

                    b.Navigation("ReviewRate");

                    b.Navigation("SocialActivityLogs");

                    b.Navigation("UserRelationshipIdRelatedUserNavigations");

                    b.Navigation("UserRelationshipIdUserNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
